name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build-dontnet:
    name: Build and test C#
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code
    
    # Set up .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Specify the .NET version to use

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build with dotnet
      run: dotnet build --configuration Release

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  build-typescript:
    name: Build and test Typescript
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    # Build the Typescript Code
    - name: Install Ddependencies
      working-directory: DotnetTemplate.Web/
      run: npm install

    # Build the Typescript Code
    - name: Build Typescript
      working-directory: DotnetTemplate.Web/
      run: npm run build

    # Runs the Typescript linter
    - name: Run Linter
      working-directory: DotnetTemplate.Web/
      run: npm run lint

    # Runs the Typescript Tests
    - name: Run Typescript Test
      working-directory: DotnetTemplate.Web/
      run: npm t
        